# Generated by Django 4.2.17 on 2024-12-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moivie',
            new_name='Movie',
        ),
    ]
